#!/bin/bash
LISTEN_ADDR=${LISTEN_ADDR:-0.0.0.0:443}

HOST_ADDR=$(ifconfig docker0|grep 'inet addr'|awk '{ print $2 }'|cut -d: -f2)

HTTP_TARGET_ADDR=--http ${HTTP_TARGET_ADDR:-$HOST_ADDR:80}
SSL_TARGET_ADDR=--ssl ${SSL_TARGET_ADDR:-$HOST_ADDR:8443}
SSH_TARGET_ADDR=--ssh ${SSH_TARGET_ADDR:-$HOST_ADDR:22}
VPN_TARGET_ADDR=--openvpn ${VPN_TARGET_ADDR:-$HOST_ADDR:1194}

out = "";
if [ -z "$HTTP_TARGET_ADDR" ]; then
  out = $out+"--http "+$HTTP_TARGET_ADDR + " "
fi
if [ -z "$SSL_TARGET_ADDR" ]; then
  out = $out+"--ssl "+$SSL_TARGET_ADDR + " "
fi
if [ -z "$SSH_TARGET_ADDR" ]; then
  out = $out+"--ssh"+$SSH_TARGET_ADDR + " " 
fi
if [ -z "$VPN_TARGET_ADDR" ]; then
  out = $out+"--openvpn "+$VPN_TARGET_ADDR + " " 
fi
if [ -z "$TRANSPARENT" ]; then
  out = $out+" --transparent"
fi


/usr/sbin/sslh -p $LISTEN_ADDR $out -f
