#!/bin/bash
LISTEN_ADDR=${LISTEN_ADDR:-0.0.0.0:443}

HOST_ADDR=$(ifconfig docker0|grep 'inet addr'|awk '{ print $2 }'|cut -d: -f2)

out=""
if [ -z "$HTTP_TARGET_ADDR" ]; then
  out = $out+"--http "+$HTTP_TARGET_ADDR + " "
else
  out = $out+"--http "+$HOST_ADDR=":80"
fi
if [ -z "$SSL_TARGET_ADDR" ]; then
  out = $out+"--ssl "+$SSL_TARGET_ADDR + " "
else
  out = $out+"--ssl "+$HOST_ADDR=":8443"
fi
if [ -z "$SSH_TARGET_ADDR" ]; then
  out = $out+"--ssh"+$SSH_TARGET_ADDR + " "
else
  out = $out+"--ssh "+$HOST_ADDR=":22"   
fi
if [ -z "$VPN_TARGET_ADDR" ]; then
  out = $out+"--openvpn "+$VPN_TARGET_ADDR + " " 
fi
if [ -z "$TRANSPARENT" ]; then
  out = $out+" --transparent"
fi
if [ -z "$SSLH_USER" ]; then
  out = $out+" --user "+$SSLH_USER + " "
else
  out = $out+" --user sslh "
fi
if [ -z "$SSLH_PIDFILE" ]; then
  out = $out+" --pidfile "+$SSLH_PIDFILE 
else
  out = $out+" --pidfile /var/run/sslh/sslh.pid "
fi

/usr/sbin/sslh -p $LISTEN_ADDR $out -f
