#!/bin/bash
LISTEN_ADDR=${LISTEN_ADDR:-0.0.0.0:443}

HOST_ADDR=$(ifconfig eth0|grep 'inet'|awk '{ print $2 }'|cut -d: -f2)

out=""
if [ -z "$HTTP_TARGET_ADDR" ]; then
  out=$out"--http "$HOST_ADDR":80 "
else
  out=$out"--http "$HTTP_TARGET_ADDR" "
fi
if [ -z "$SSL_TARGET_ADDR" ]; then
  out=$out"--ssl "$HOST_ADDR":8443 "
else
  out=$out"--ssl "$SSL_TARGET_ADDR" "
fi
if [ -z "$SSH_TARGET_ADDR" ]; then
  out=$out"--ssh "$HOST_ADDR":22 "   
else
  out=$out"--ssh"$SSH_TARGET_ADDR" "
fi
if ! [ -z "$VPN_TARGET_ADDR" ]; then
  out=$out"--openvpn "$VPN_TARGET_ADDR" " 
fi
if ! [ -z "$TRANSPARENT" ]; then
  out=$out" --transparent "
fi
if [ -z "$SSLH_USER" ]; then
  out=$out" --user sslh "
else
  out=$out" --user "$SSLH_USER" "
fi
if [ -z "$SSLH_PIDFILE" ]; then
  out=$out" --pidfile /var/run/sslh/sslh.pid "
else
  out=$out" --pidfile "$SSLH_PIDFILE 
fi

/usr/sbin/sslh -p $LISTEN_ADDR $out -f
